// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXaBGI0c1BbTpl09LQvLOhwKYXQytrFUc',
    appId: '1:316494236811:android:9407e2ae06c70eaabd988e',
    messagingSenderId: '316494236811',
    projectId: 'my-smart-agriculture-c9a33',
    databaseURL: 'https://my-smart-agriculture-c9a33-default-rtdb.firebaseio.com',
    storageBucket: 'my-smart-agriculture-c9a33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9D3mqoxZiFrrRUQmK1Wh7s14YL8iNqlQ',
    appId: '1:316494236811:ios:3052b3a0a0fbd3d0bd988e',
    messagingSenderId: '316494236811',
    projectId: 'my-smart-agriculture-c9a33',
    databaseURL: 'https://my-smart-agriculture-c9a33-default-rtdb.firebaseio.com',
    storageBucket: 'my-smart-agriculture-c9a33.appspot.com',
    iosClientId: '316494236811-1bfkfagequ6fch976a3667ld25pk6erj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAgriProject',
  );
}
